const ACTION_TYPES = {

    NOTIFICATION: 'NOTIFICATION',

    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_REFRESH: 'AUTH_REFRESH',

    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',

    AUTH_SIGN_UP_REQUEST: 'AUTH_SIGN_UP_REQUEST',
    AUTH_SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
    AUTH_SIGN_UP_ERROR: 'AUTH_SIGN_UP_ERROR',

    AUTH_SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
    AUTH_SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
    AUTH_SIGN_IN_ERROR: 'AUTH_SIGN_IN_ERROR',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: ' UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: ' UPDATE_USER_ERROR',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: ' GET_USER_SUCCESS',
    GET_USER_ERROR: ' GET_USER_ERROR',

    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: ' GET_TASKS_SUCCESS',
    GET_TASKS_ERROR: ' GET_TASKS_ERROR',

    CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
    CREATE_TASK_SUCCESS: ' CREATE_TASK_SUCCESS',
    CREATE_TASK_ERROR: ' CREATE_TASK_ERROR',

    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',

    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_ERROR: '  DELETE_TASK_ERROR',
}

export default ACTION_TYPES